import { Type } from "@mariozechner/pi-ai";
import type { ToolDefinition } from "@mariozechner/pi-coding-agent";
import {
  managerCommandProposalSchema,
  type ManagerCommandProposal,
} from "../manager-command-commit.js";

function createProposalTool(args: {
  name: string;
  label: string;
  description: string;
  promptSnippet: string;
  parameters: ReturnType<typeof Type.Object>;
  commandType: ManagerCommandProposal["commandType"];
}): ToolDefinition {
  return {
    name: args.name,
    label: args.label,
    description: args.description,
    promptSnippet: args.promptSnippet,
    parameters: args.parameters,
    async execute(_toolCallId, params) {
      const proposal = managerCommandProposalSchema.parse({
        commandType: args.commandType,
        ...(params as Record<string, unknown>),
      });
      return {
        content: [{ type: "text", text: "Command proposal recorded." }],
        details: { proposal },
      };
    },
  };
}

export function createManagerProposalTools(): ToolDefinition[] {
  return [
    createProposalTool({
      name: "propose_create_issue",
      label: "Propose Create Issue",
      description: "Propose creating a single Linear issue. This does not execute the mutation.",
      promptSnippet: "Use this when the user clearly wants a single new tracked task.",
      commandType: "create_issue",
      parameters: Type.Object({
        planningReason: Type.Optional(Type.String({ description: "Usually single-issue." })),
        issue: Type.Object({
          title: Type.String({ description: "Issue title." }),
          description: Type.String({ description: "Markdown description." }),
          state: Type.Optional(Type.String({ description: "Optional initial state." })),
          dueDate: Type.Optional(Type.String({ description: "Due date in YYYY-MM-DD." })),
          assigneeMode: Type.String({ description: "assign | leave-unassigned. Decide explicitly whether to assign an owner." }),
          assignee: Type.Optional(Type.String({ description: "Assignee identifier. Required when assigneeMode=assign." })),
          parent: Type.Optional(Type.String({ description: "Optional parent issue identifier." })),
          priority: Type.Optional(Type.Number({ description: "Priority 1-4." })),
        }),
        threadParentHandling: Type.String({
          description: "ignore | attach. Decide explicitly whether this issue should become a child of the existing thread parent issue.",
        }),
        duplicateHandling: Type.String({
          description: "clarify | reuse-existing | reuse-and-attach-parent | create-new. Decide explicitly how to handle existing duplicate issues.",
        }),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_create_issue_batch",
      label: "Propose Create Issue Batch",
      description: "Propose creating a parent issue plus child issues. This does not execute the mutation.",
      promptSnippet: "Use this when a request should be broken into a parent and execution-sized child tasks. Each batch may contain at most 8 children; split larger sets into multiple create_issue_batch proposals in the same turn.",
      commandType: "create_issue_batch",
      parameters: Type.Object({
        planningReason: Type.String({ description: "Usually complex-request or research-first." }),
        parent: Type.Object({
          title: Type.String({ description: "Parent issue title." }),
          description: Type.String({ description: "Parent issue description." }),
          state: Type.Optional(Type.String({ description: "Optional initial state." })),
          dueDate: Type.Optional(Type.String({ description: "Due date in YYYY-MM-DD." })),
          assigneeMode: Type.String({ description: "assign | leave-unassigned. Decide explicitly whether to assign the parent issue." }),
          assignee: Type.Optional(Type.String({ description: "Assignee identifier. Required when assigneeMode=assign." })),
          parent: Type.Optional(Type.String({ description: "Optional grandparent issue identifier." })),
          priority: Type.Optional(Type.Number({ description: "Priority 1-4." })),
        }),
        children: Type.Array(Type.Object({
          title: Type.String({ description: "Child issue title." }),
          description: Type.String({ description: "Child issue description." }),
          state: Type.Optional(Type.String({ description: "Optional initial state." })),
          dueDate: Type.Optional(Type.String({ description: "Due date in YYYY-MM-DD." })),
          assigneeMode: Type.String({ description: "assign | leave-unassigned. Decide explicitly whether to assign this child issue." }),
          assignee: Type.Optional(Type.String({ description: "Assignee identifier. Required when assigneeMode=assign." })),
          parent: Type.Optional(Type.String({ description: "Optional parent issue identifier override." })),
          priority: Type.Optional(Type.Number({ description: "Priority 1-4." })),
          kind: Type.Optional(Type.String({ description: "execution or research." })),
        })),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_create_project",
      label: "Propose Create Project",
      description: "Propose creating a Linear project. This does not execute the mutation.",
      promptSnippet: "Use this when the user clearly wants a new Linear project rather than an issue.",
      commandType: "create_project",
      parameters: Type.Object({
        name: Type.String({ description: "Project name." }),
        description: Type.Optional(Type.String({ description: "Optional project description." })),
        teamKeys: Type.Optional(Type.Array(Type.String({ description: "Optional team keys. Omit to use the fixed default team." }))),
        lead: Type.Optional(Type.String({ description: "Optional project lead username, email, or @me." })),
        status: Type.Optional(Type.String({ description: "Optional project status such as planned, started, paused, backlog, completed, or canceled." })),
        startDate: Type.Optional(Type.String({ description: "Optional start date in YYYY-MM-DD." })),
        targetDate: Type.Optional(Type.String({ description: "Optional target completion date in YYYY-MM-DD." })),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_update_project",
      label: "Propose Update Project",
      description: "Propose updating a Linear project. This does not execute the mutation.",
      promptSnippet: "Use this when the user explicitly asks to rename or otherwise update an existing Linear project.",
      commandType: "update_project",
      parameters: Type.Object({
        projectId: Type.String({ description: "Project id or slug used as the update target." }),
        name: Type.Optional(Type.String({ description: "Optional project name patch." })),
        description: Type.Optional(Type.String({ description: "Optional project description patch." })),
        teamKeys: Type.Optional(Type.Array(Type.String({ description: "Optional full replacement team key set." }))),
        lead: Type.Optional(Type.String({ description: "Optional project lead username, email, or @me." })),
        status: Type.Optional(Type.String({ description: "Optional project status patch." })),
        startDate: Type.Optional(Type.String({ description: "Optional start date patch in YYYY-MM-DD." })),
        targetDate: Type.Optional(Type.String({ description: "Optional target date patch in YYYY-MM-DD." })),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_link_existing_issue",
      label: "Propose Link Existing Issue",
      description: "Propose using an existing Linear issue for one requested work item. This does not execute any Linear mutation.",
      promptSnippet: "Use this only after inspecting likely existing issues with linear_search_issues or linear_get_issue_facts and deciding one item should reuse an existing issue instead of creating a new one.",
      commandType: "link_existing_issue",
      parameters: Type.Object({
        issueId: Type.String({ description: "Existing issue identifier like AIC-123." }),
        reasonSummary: Type.String({ description: "Short reason for reusing this existing issue." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary from search results or issue facts." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_update_issue_status",
      label: "Propose Update Issue Status",
      description: "Propose a progress, completed, or blocked update. This does not execute the mutation.",
      promptSnippet: "Use this when the user reports progress, completion, or blocked status on an existing issue.",
      commandType: "update_issue_status",
      parameters: Type.Object({
        issueId: Type.String({ description: "Issue identifier like AIC-123." }),
        signal: Type.String({ description: "progress | completed | blocked" }),
        commentBody: Type.Optional(Type.String({ description: "Optional markdown body for the update." })),
        state: Type.Optional(Type.String({ description: "Optional target state name." })),
        dueDate: Type.Optional(Type.String({ description: "Optional due date in YYYY-MM-DD when the user states a new target completion date." })),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_update_issue_priority",
      label: "Propose Update Issue Priority",
      description: "Propose changing an issue priority without changing its state. This does not execute the mutation.",
      promptSnippet: "Use this when the user asks to lower or raise priority, for example 後回し, 優先度を下げる, or 優先度を上げる.",
      commandType: "update_issue_priority",
      parameters: Type.Object({
        issueId: Type.String({ description: "Issue identifier like AIC-123." }),
        priority: Type.Number({ description: "Priority 1-4. Use Low=4 by default for vague deprioritize requests like 後回し or 優先度を下げて." }),
        commentBody: Type.Optional(Type.String({ description: "Optional markdown comment to record the rationale." })),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_assign_issue",
      label: "Propose Assign Issue",
      description: "Propose changing an issue assignee. This does not execute the mutation.",
      promptSnippet: "Use this when ownership should change.",
      commandType: "assign_issue",
      parameters: Type.Object({
        issueId: Type.String({ description: "Issue identifier like AIC-123." }),
        assignee: Type.String({ description: "Assignee display name, email, or username." }),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_add_comment",
      label: "Propose Add Comment",
      description: "Propose adding a markdown comment to an issue. This does not execute the mutation.",
      promptSnippet: "Use this when the right action is to record context on an issue without changing status.",
      commandType: "add_comment",
      parameters: Type.Object({
        issueId: Type.String({ description: "Issue identifier like AIC-123." }),
        body: Type.String({ description: "Markdown comment body." }),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_add_relation",
      label: "Propose Add Relation",
      description: "Propose adding a relation between issues. This does not execute the mutation.",
      promptSnippet: "Use this when a dependency should be made explicit.",
      commandType: "add_relation",
      parameters: Type.Object({
        issueId: Type.String({ description: "Source issue ID." }),
        relatedIssueId: Type.String({ description: "Related issue ID." }),
        relationType: Type.String({ description: "blocks or blocked-by." }),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_set_issue_parent",
      label: "Propose Set Issue Parent",
      description: "Propose making one issue a child of another issue. This does not execute the mutation.",
      promptSnippet: "Use this when the user explicitly asks to make AIC-123 a child task of AIC-456.",
      commandType: "set_issue_parent",
      parameters: Type.Object({
        issueId: Type.String({ description: "Child issue identifier like AIC-123." }),
        parentIssueId: Type.String({ description: "Parent issue identifier like AIC-456." }),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_create_scheduler_job",
      label: "Propose Create Scheduler Job",
      description: "Propose creating a custom scheduler job. This does not execute the mutation.",
      promptSnippet: "Use this when the user wants to add a new recurring or one-shot custom scheduler job from Slack.",
      commandType: "create_scheduler_job",
      parameters: Type.Object({
        jobId: Type.String({ description: "Stable custom job id such as daily-task-check." }),
        channelId: Type.Optional(Type.String({ description: "Optional target channel id. Omit to use the control room channel." })),
        prompt: Type.String({ description: "Prompt the scheduler job should execute." }),
        kind: Type.String({ description: "at | every | daily | weekly" }),
        at: Type.Optional(Type.String({ description: "ISO datetime for one-shot runs." })),
        everySec: Type.Optional(Type.Number({ description: "Interval seconds for kind=every." })),
        time: Type.Optional(Type.String({ description: "HH:MM for daily or weekly jobs." })),
        weekday: Type.Optional(Type.String({ description: "mon | tue | wed | thu | fri | sat | sun for weekly jobs." })),
        enabled: Type.Optional(Type.Boolean({ description: "Whether the custom job should start enabled." })),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_update_scheduler_job",
      label: "Propose Update Scheduler Job",
      description: "Propose updating a custom scheduler job. This does not execute the mutation.",
      promptSnippet: "Use this when the user wants to update, stop, resume, or retime a custom scheduler job.",
      commandType: "update_scheduler_job",
      parameters: Type.Object({
        jobId: Type.String({ description: "Existing custom job id." }),
        enabled: Type.Optional(Type.Boolean({ description: "Optional enabled flag." })),
        channelId: Type.Optional(Type.String({ description: "Optional channel id patch." })),
        prompt: Type.Optional(Type.String({ description: "Optional prompt patch." })),
        kind: Type.Optional(Type.String({ description: "Optional replacement schedule kind: at | every | daily | weekly." })),
        at: Type.Optional(Type.String({ description: "Optional ISO datetime patch for kind=at." })),
        everySec: Type.Optional(Type.Number({ description: "Optional seconds patch for kind=every." })),
        time: Type.Optional(Type.String({ description: "Optional HH:MM patch for daily or weekly jobs." })),
        weekday: Type.Optional(Type.String({ description: "Optional weekday patch for weekly jobs." })),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_delete_scheduler_job",
      label: "Propose Delete Scheduler Job",
      description: "Propose deleting a custom scheduler job. This does not execute the mutation.",
      promptSnippet: "Use this only for custom scheduler jobs. Built-in schedules should be disabled with propose_update_builtin_schedule instead.",
      commandType: "delete_scheduler_job",
      parameters: Type.Object({
        jobId: Type.String({ description: "Existing custom job id." }),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_update_builtin_schedule",
      label: "Propose Update Builtin Schedule",
      description: "Propose updating a built-in review or heartbeat schedule. This does not execute the mutation.",
      promptSnippet: "Use this for morning/evening/weekly review or heartbeat changes. Delete on a built-in means disable it instead of removing it.",
      commandType: "update_builtin_schedule",
      parameters: Type.Object({
        builtinId: Type.String({ description: "morning-review | evening-review | weekly-review | heartbeat" }),
        enabled: Type.Optional(Type.Boolean({ description: "Optional enable or disable flag." })),
        time: Type.Optional(Type.String({ description: "Optional HH:MM patch for review schedules." })),
        weekday: Type.Optional(Type.String({ description: "Optional weekday patch for weekly-review." })),
        intervalMin: Type.Optional(Type.Number({ description: "Optional heartbeat interval in minutes." })),
        activeLookbackHours: Type.Optional(Type.Number({ description: "Optional heartbeat active lookback window in hours." })),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_run_scheduler_job_now",
      label: "Propose Run Scheduler Job Now",
      description: "Propose running one custom scheduler job immediately. This does not execute the mutation.",
      promptSnippet: "Use this when the user asks to run a custom scheduler job immediately for testing or a one-off check.",
      commandType: "run_scheduler_job_now",
      parameters: Type.Object({
        jobId: Type.String({ description: "Existing custom scheduler job id." }),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_post_slack_message",
      label: "Propose Post Slack Message",
      description: "Propose posting one mention-tagged Slack message to the current thread or control room root. This does not execute the mutation.",
      promptSnippet: "Use this only for explicit Slack requests like X にメンションして Y と送って. Call workspace_get_owner_map first, resolve exactly one target, default to current-thread unless the user explicitly says control room, and do not include any extra mention tokens in messageText.",
      commandType: "post_slack_message",
      parameters: Type.Object({
        destination: Type.String({ description: "current-thread | control-room-root" }),
        mentionSlackUserId: Type.String({ description: "Resolved Slack user id from owner-map.json." }),
        targetLabel: Type.String({ description: "Human-readable target label such as y.kakui or kyaukyuai." }),
        messageText: Type.String({ description: "Final message body without the target mention token." }),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_update_workspace_memory",
      label: "Propose Update Workspace Memory",
      description: "Propose saving durable operator-specific knowledge into workspace MEMORY. This does not execute the mutation.",
      promptSnippet: "Use this only when the user explicitly asks to save durable facts, terminology, project context, members, roadmap milestones, or preferences into MEMORY.",
      commandType: "update_workspace_memory",
      parameters: Type.Object({
        sourceLabel: Type.Optional(Type.String({ description: "Optional short source label such as the Notion page title." })),
        entries: Type.Array(Type.Object({
          category: Type.String({ description: "One of project-overview | members-and-roles | roadmap-and-milestones | terminology | preferences | context. Legacy people-and-projects is accepted only for compatibility." }),
          projectName: Type.Optional(Type.String({ description: "Required for project-overview, members-and-roles, and roadmap-and-milestones." })),
          summary: Type.String({ description: "Short stable summary used for dedupe." }),
          canonicalText: Type.String({ description: "Stable MEMORY sentence to save." }),
        })),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_replace_workspace_text_file",
      label: "Propose Replace Workspace Text File",
      description: "Propose updating AGENDA_TEMPLATE.md or HEARTBEAT.md by replacing the full file contents. This does not execute the mutation.",
      promptSnippet: "Use this for explicit Slack requests to update or replace the whole agenda template or heartbeat prompt. Read the current file first with the matching workspace_get tool. Do not say that file editing is unavailable.",
      commandType: "replace_workspace_text_file",
      parameters: Type.Object({
        target: Type.String({ description: "agenda-template | heartbeat-prompt" }),
        content: Type.String({ description: "Final full file content after replacement." }),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_update_owner_map",
      label: "Propose Update Owner Map",
      description: "Propose a structured owner-map.json change. This does not execute the mutation.",
      promptSnippet: "Use this only for explicit Slack requests to update owner-map.json. Call workspace_get_owner_map first and propose one structured operation at a time. Do not say that file editing is unavailable.",
      commandType: "update_owner_map",
      parameters: Type.Object({
        operation: Type.String({ description: "set-default-owner | upsert-entry | delete-entry" }),
        entryId: Type.Optional(Type.String({ description: "Target entry id. Required for upsert-entry and delete-entry." })),
        defaultOwner: Type.Optional(Type.String({ description: "New default owner. Required for set-default-owner." })),
        linearAssignee: Type.Optional(Type.String({ description: "Linear assignee label. Required for upsert-entry." })),
        slackUserId: Type.Optional(Type.String({ description: "Optional Slack user id for upsert-entry." })),
        domains: Type.Optional(Type.Array(Type.String({ description: "Optional domains for upsert-entry." }))),
        keywords: Type.Optional(Type.Array(Type.String({ description: "Optional keywords for upsert-entry." }))),
        primary: Type.Optional(Type.Boolean({ description: "Optional primary flag for upsert-entry." })),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_create_notion_agenda",
      label: "Propose Create Notion Agenda",
      description: "Propose creating a Notion agenda page. This does not execute the mutation.",
      promptSnippet: "Use this when the user explicitly asks to create an agenda in Notion.",
      commandType: "create_notion_agenda",
      parameters: Type.Object({
        title: Type.String({ description: "Agenda page title." }),
        summary: Type.Optional(Type.String({ description: "Optional short summary or purpose shown near the top of the page." })),
        parentPageId: Type.Optional(Type.String({ description: "Optional Notion parent page ID. Omit this to use the configured default agenda parent." })),
        sections: Type.Optional(Type.Array(Type.Object({
          heading: Type.String({ description: "Section heading such as 目的 or 議題." }),
          paragraph: Type.Optional(Type.String({ description: "Optional paragraph body for the section." })),
          bullets: Type.Optional(Type.Array(Type.String({ description: "Optional bullet items for the section." }))),
        }))),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_update_notion_page",
      label: "Propose Update Notion Page",
      description: "Propose updating one existing Notion page. This does not execute the mutation.",
      promptSnippet: "Use this when the user asks to update a Notion page, retitle it, append notes, or replace one named section on a Cogito-managed page.",
      commandType: "update_notion_page",
      parameters: Type.Object({
        pageId: Type.String({ description: "Target Notion page ID." }),
        mode: Type.String({ description: "append | replace_section" }),
        title: Type.Optional(Type.String({ description: "Optional new page title." })),
        summary: Type.Optional(Type.String({ description: "Optional summary paragraph to append near the end of the page." })),
        sections: Type.Optional(Type.Array(Type.Object({
          heading: Type.String({ description: "Section heading such as 決定事項 or 次のアクション." }),
          paragraph: Type.Optional(Type.String({ description: "Optional paragraph body for the section." })),
          bullets: Type.Optional(Type.Array(Type.String({ description: "Optional bullet items for the section." }))),
        }))),
        sectionHeading: Type.Optional(Type.String({ description: "Required for replace_section. Exact top-level heading_2 label to replace, such as 議題 or 次のアクション." })),
        paragraph: Type.Optional(Type.String({ description: "Optional replacement paragraph for replace_section." })),
        bullets: Type.Optional(Type.Array(Type.String({ description: "Optional replacement bullet items for replace_section." }))),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_archive_notion_page",
      label: "Propose Archive Notion Page",
      description: "Propose archiving one existing Notion page. This does not execute the mutation.",
      promptSnippet: "Use this when the user asks to delete, archive, or trash a Notion page. In this scope, delete means archive/trash.",
      commandType: "archive_notion_page",
      parameters: Type.Object({
        pageId: Type.String({ description: "Target Notion page ID." }),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_followup_resolution",
      label: "Propose Followup Resolution",
      description: "Propose resolving an outstanding follow-up. This does not execute the mutation.",
      promptSnippet: "Use this when a thread reply answers a follow-up request.",
      commandType: "resolve_followup",
      parameters: Type.Object({
        issueId: Type.String({ description: "Issue identifier like AIC-123." }),
        answered: Type.Boolean({ description: "Whether the follow-up is sufficiently answered." }),
        confidence: Type.Number({ description: "Confidence between 0 and 1." }),
        answerKind: Type.Optional(Type.String({ description: "Short answer kind label." })),
        requestKind: Type.Optional(Type.String({ description: "status | blocked-details | owner | due-date" })),
        responseText: Type.String({ description: "User response text." }),
        acceptableAnswerHint: Type.Optional(Type.String({ description: "Preferred answer format hint." })),
        extractedFields: Type.Optional(Type.Object({}, { additionalProperties: Type.String() })),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_review_followup",
      label: "Propose Review Followup",
      description: "Propose a proactive follow-up request for review or heartbeat. This does not execute the mutation.",
      promptSnippet: "Use this when a review should ask for one concrete follow-up.",
      commandType: "review_followup",
      parameters: Type.Object({
        issueId: Type.String({ description: "Issue identifier like AIC-123." }),
        issueTitle: Type.String({ description: "Issue title." }),
        riskCategory: Type.String({ description: "Primary risk category." }),
        requestKind: Type.String({ description: "status | blocked-details | owner | due-date" }),
        request: Type.String({ description: "Follow-up request text." }),
        acceptableAnswerHint: Type.Optional(Type.String({ description: "Preferred answer format." })),
        assigneeDisplayName: Type.Optional(Type.String({ description: "Assignee display name." })),
        slackUserId: Type.Optional(Type.String({ description: "Slack user ID if known." })),
        source: Type.Optional(Type.Object({
          channelId: Type.String({ description: "Source channel ID." }),
          rootThreadTs: Type.String({ description: "Source thread timestamp." }),
          sourceMessageTs: Type.String({ description: "Source message timestamp." }),
        })),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
  ];
}
