import { Type } from "@mariozechner/pi-ai";
import type { ToolDefinition } from "@mariozechner/pi-coding-agent";
import { createProposalTool } from "./proposal-tool-factory.js";

export function createWorkspaceProposalTools(): ToolDefinition[] {
  return [
    createProposalTool({
      name: "propose_post_slack_message",
      label: "Propose Post Slack Message",
      description: "Propose posting one mention-tagged Slack message to the current thread or control room root. This does not execute the mutation.",
      promptSnippet: "Use this only for explicit Slack requests like X にメンションして Y と送って. Call workspace_get_owner_map first, resolve exactly one target, default to current-thread unless the user explicitly says control room, and do not include any extra mention tokens in messageText.",
      commandType: "post_slack_message",
      parameters: Type.Object({
        destination: Type.String({ description: "current-thread | control-room-root" }),
        mentionSlackUserId: Type.String({ description: "Resolved Slack user id from owner-map.json." }),
        targetLabel: Type.String({ description: "Human-readable target label such as y.kakui or kyaukyuai." }),
        messageText: Type.String({ description: "Final message body without the target mention token." }),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_update_workspace_memory",
      label: "Propose Update Workspace Memory",
      description: "Propose saving durable operator-specific knowledge into workspace MEMORY. This does not execute the mutation.",
      promptSnippet: "Use this only when the user explicitly asks to save durable facts, terminology, project context, members, roadmap milestones, or preferences into MEMORY.",
      commandType: "update_workspace_memory",
      parameters: Type.Object({
        sourceLabel: Type.Optional(Type.String({ description: "Optional short source label such as the Notion page title." })),
        entries: Type.Array(Type.Object({
          category: Type.String({ description: "One of project-overview | members-and-roles | roadmap-and-milestones | terminology | preferences | context. Legacy people-and-projects is accepted only for compatibility." }),
          projectName: Type.Optional(Type.String({ description: "Required for project-overview, members-and-roles, and roadmap-and-milestones." })),
          summary: Type.String({ description: "Short stable summary used for dedupe." }),
          canonicalText: Type.String({ description: "Stable MEMORY sentence to save." }),
        })),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_replace_workspace_text_file",
      label: "Propose Replace Workspace Text File",
      description: "Propose updating AGENDA_TEMPLATE.md or HEARTBEAT.md by replacing the full file contents. This does not execute the mutation.",
      promptSnippet: "Use this for explicit Slack requests to update or replace the whole agenda template or heartbeat prompt. Read the current file first with the matching workspace_get tool. Do not say that file editing is unavailable.",
      commandType: "replace_workspace_text_file",
      parameters: Type.Object({
        target: Type.String({ description: "agenda-template | heartbeat-prompt" }),
        content: Type.String({ description: "Final full file content after replacement." }),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_update_owner_map",
      label: "Propose Update Owner Map",
      description: "Propose a structured owner-map.json change. This does not execute the mutation.",
      promptSnippet: "Use this only for explicit Slack requests to update owner-map.json. Call workspace_get_owner_map first and propose one structured operation at a time. Do not say that file editing is unavailable.",
      commandType: "update_owner_map",
      parameters: Type.Object({
        operation: Type.String({ description: "set-default-owner | upsert-entry | delete-entry" }),
        entryId: Type.Optional(Type.String({ description: "Target entry id. Required for upsert-entry and delete-entry." })),
        defaultOwner: Type.Optional(Type.String({ description: "New default owner. Required for set-default-owner." })),
        linearAssignee: Type.Optional(Type.String({ description: "Linear assignee label. Required for upsert-entry." })),
        slackUserId: Type.Optional(Type.String({ description: "Optional Slack user id for upsert-entry." })),
        domains: Type.Optional(Type.Array(Type.String({ description: "Optional domains for upsert-entry." }))),
        keywords: Type.Optional(Type.Array(Type.String({ description: "Optional keywords for upsert-entry." }))),
        primary: Type.Optional(Type.Boolean({ description: "Optional primary flag for upsert-entry." })),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_create_notion_agenda",
      label: "Propose Create Notion Agenda",
      description: "Propose creating a Notion agenda page. This does not execute the mutation.",
      promptSnippet: "Use this when the user explicitly asks to create an agenda in Notion.",
      commandType: "create_notion_agenda",
      parameters: Type.Object({
        title: Type.String({ description: "Agenda page title." }),
        summary: Type.Optional(Type.String({ description: "Optional short summary or purpose shown near the top of the page." })),
        parentPageId: Type.Optional(Type.String({ description: "Optional Notion parent page ID. Omit this to use the configured default agenda parent." })),
        sections: Type.Optional(Type.Array(Type.Object({
          heading: Type.String({ description: "Section heading such as 目的 or 議題." }),
          paragraph: Type.Optional(Type.String({ description: "Optional paragraph body for the section." })),
          bullets: Type.Optional(Type.Array(Type.String({ description: "Optional bullet items for the section." }))),
        }))),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_update_notion_page",
      label: "Propose Update Notion Page",
      description: "Propose updating one existing Notion page. This does not execute the mutation.",
      promptSnippet: "Use this when the user asks to update a Notion page, retitle it, append notes, or replace one named section on a Cogito-managed page.",
      commandType: "update_notion_page",
      parameters: Type.Object({
        pageId: Type.String({ description: "Target Notion page ID." }),
        mode: Type.String({ description: "append | replace_section" }),
        title: Type.Optional(Type.String({ description: "Optional new page title." })),
        summary: Type.Optional(Type.String({ description: "Optional summary paragraph to append near the end of the page." })),
        sections: Type.Optional(Type.Array(Type.Object({
          heading: Type.String({ description: "Section heading such as 決定事項 or 次のアクション." }),
          paragraph: Type.Optional(Type.String({ description: "Optional paragraph body for the section." })),
          bullets: Type.Optional(Type.Array(Type.String({ description: "Optional bullet items for the section." }))),
        }))),
        sectionHeading: Type.Optional(Type.String({ description: "Required for replace_section. Exact top-level heading_2 label to replace, such as 議題 or 次のアクション." })),
        paragraph: Type.Optional(Type.String({ description: "Optional replacement paragraph for replace_section." })),
        bullets: Type.Optional(Type.Array(Type.String({ description: "Optional replacement bullet items for replace_section." }))),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_archive_notion_page",
      label: "Propose Archive Notion Page",
      description: "Propose archiving one existing Notion page. This does not execute the mutation.",
      promptSnippet: "Use this when the user asks to delete, archive, or trash a Notion page. In this scope, delete means archive/trash.",
      commandType: "archive_notion_page",
      parameters: Type.Object({
        pageId: Type.String({ description: "Target Notion page ID." }),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
  ];
}
