import { Type } from "@mariozechner/pi-ai";
import type { ToolDefinition } from "@mariozechner/pi-coding-agent";
import { createProposalTool } from "./proposal-tool-factory.js";

export function createWorkItemProposalTools(): ToolDefinition[] {
  return [
    createProposalTool({
      name: "propose_create_issue",
      label: "Propose Create Issue",
      description: "Propose creating a single Linear issue. This does not execute the mutation.",
      promptSnippet: "Use this when the user clearly wants a single new tracked task.",
      commandType: "create_issue",
      parameters: Type.Object({
        planningReason: Type.Optional(Type.String({ description: "Usually single-issue." })),
        issue: Type.Object({
          title: Type.String({ description: "Issue title." }),
          description: Type.String({ description: "Markdown description." }),
          state: Type.Optional(Type.String({ description: "Optional initial state." })),
          dueDate: Type.Optional(Type.String({ description: "Due date in YYYY-MM-DD." })),
          project: Type.Optional(Type.String({ description: "Exact Linear project name or slug ID when the user explicitly wants the issue inside a project." })),
          assigneeMode: Type.String({ description: "assign | leave-unassigned. Decide explicitly whether to assign an owner." }),
          assignee: Type.Optional(Type.String({ description: "Assignee identifier. Required when assigneeMode=assign." })),
          parent: Type.Optional(Type.String({ description: "Optional parent issue identifier." })),
          priority: Type.Optional(Type.Number({ description: "Priority 1-4." })),
        }),
        threadParentHandling: Type.String({
          description: "ignore | attach. Decide explicitly whether this issue should become a child of the existing thread parent issue.",
        }),
        duplicateHandling: Type.String({
          description: "clarify | reuse-existing | reuse-and-attach-parent | create-new. Decide explicitly how to handle existing duplicate issues.",
        }),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_create_issue_batch",
      label: "Propose Create Issue Batch",
      description: "Propose creating a parent issue plus child issues. This does not execute the mutation.",
      promptSnippet: "Use this when a request should be broken into a parent and execution-sized child tasks. Each batch may contain at most 8 children; split larger sets into multiple create_issue_batch proposals in the same turn.",
      commandType: "create_issue_batch",
      parameters: Type.Object({
        planningReason: Type.String({ description: "Usually complex-request or research-first." }),
        parent: Type.Object({
          title: Type.String({ description: "Parent issue title." }),
          description: Type.String({ description: "Parent issue description." }),
          state: Type.Optional(Type.String({ description: "Optional initial state." })),
          dueDate: Type.Optional(Type.String({ description: "Due date in YYYY-MM-DD." })),
          project: Type.Optional(Type.String({ description: "Exact Linear project name or slug ID when the whole batch should belong to a project." })),
          assigneeMode: Type.String({ description: "assign | leave-unassigned. Decide explicitly whether to assign the parent issue." }),
          assignee: Type.Optional(Type.String({ description: "Assignee identifier. Required when assigneeMode=assign." })),
          parent: Type.Optional(Type.String({ description: "Optional grandparent issue identifier." })),
          priority: Type.Optional(Type.Number({ description: "Priority 1-4." })),
        }),
        children: Type.Array(Type.Object({
          title: Type.String({ description: "Child issue title." }),
          description: Type.String({ description: "Child issue description." }),
          state: Type.Optional(Type.String({ description: "Optional initial state." })),
          dueDate: Type.Optional(Type.String({ description: "Due date in YYYY-MM-DD." })),
          assigneeMode: Type.String({ description: "assign | leave-unassigned. Decide explicitly whether to assign this child issue." }),
          assignee: Type.Optional(Type.String({ description: "Assignee identifier. Required when assigneeMode=assign." })),
          parent: Type.Optional(Type.String({ description: "Optional parent issue identifier override." })),
          priority: Type.Optional(Type.Number({ description: "Priority 1-4." })),
          kind: Type.Optional(Type.String({ description: "execution or research." })),
        })),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_create_project",
      label: "Propose Create Project",
      description: "Propose creating a Linear project. This does not execute the mutation.",
      promptSnippet: "Use this when the user clearly wants a new Linear project rather than an issue.",
      commandType: "create_project",
      parameters: Type.Object({
        name: Type.String({ description: "Project name." }),
        description: Type.Optional(Type.String({ description: "Optional project description." })),
        teamKeys: Type.Optional(Type.Array(Type.String({ description: "Optional team keys. Omit to use the fixed default team." }))),
        lead: Type.Optional(Type.String({ description: "Optional project lead username, email, or @me." })),
        status: Type.Optional(Type.String({ description: "Optional project status such as planned, started, paused, backlog, completed, or canceled." })),
        startDate: Type.Optional(Type.String({ description: "Optional start date in YYYY-MM-DD." })),
        targetDate: Type.Optional(Type.String({ description: "Optional target completion date in YYYY-MM-DD." })),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_update_project",
      label: "Propose Update Project",
      description: "Propose updating a Linear project. This does not execute the mutation.",
      promptSnippet: "Use this when the user explicitly asks to rename or otherwise update an existing Linear project.",
      commandType: "update_project",
      parameters: Type.Object({
        projectId: Type.String({ description: "Project id or slug used as the update target." }),
        name: Type.Optional(Type.String({ description: "Optional project name patch." })),
        description: Type.Optional(Type.String({ description: "Optional project description patch." })),
        teamKeys: Type.Optional(Type.Array(Type.String({ description: "Optional full replacement team key set." }))),
        lead: Type.Optional(Type.String({ description: "Optional project lead username, email, or @me." })),
        status: Type.Optional(Type.String({ description: "Optional project status patch." })),
        startDate: Type.Optional(Type.String({ description: "Optional start date patch in YYYY-MM-DD." })),
        targetDate: Type.Optional(Type.String({ description: "Optional target date patch in YYYY-MM-DD." })),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_link_existing_issue",
      label: "Propose Link Existing Issue",
      description: "Propose using an existing Linear issue for one requested work item. This does not execute any Linear mutation.",
      promptSnippet: "Use this only after inspecting likely existing issues with linear_search_issues or linear_get_issue_facts and deciding one item should reuse an existing issue instead of creating a new one.",
      commandType: "link_existing_issue",
      parameters: Type.Object({
        issueId: Type.String({ description: "Existing issue identifier like AIC-123." }),
        reasonSummary: Type.String({ description: "Short reason for reusing this existing issue." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary from search results or issue facts." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_update_issue_status",
      label: "Propose Update Issue Status",
      description: "Propose a progress, completed, or blocked update. This does not execute the mutation.",
      promptSnippet: "Use this when the user reports progress, completion, or blocked status on an existing issue.",
      commandType: "update_issue_status",
      parameters: Type.Object({
        issueId: Type.String({ description: "Issue identifier like AIC-123." }),
        signal: Type.String({ description: "progress | completed | blocked" }),
        commentBody: Type.Optional(Type.String({ description: "Optional markdown body for the update." })),
        state: Type.Optional(Type.String({ description: "Optional target state name." })),
        dueDate: Type.Optional(Type.String({ description: "Optional due date in YYYY-MM-DD when the user states a new target completion date." })),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_update_issue_priority",
      label: "Propose Update Issue Priority",
      description: "Propose changing an issue priority without changing its state. This does not execute the mutation.",
      promptSnippet: "Use this when the user asks to lower or raise priority, for example 後回し, 優先度を下げる, or 優先度を上げる.",
      commandType: "update_issue_priority",
      parameters: Type.Object({
        issueId: Type.String({ description: "Issue identifier like AIC-123." }),
        priority: Type.Number({ description: "Priority 1-4. Use Low=4 by default for vague deprioritize requests like 後回し or 優先度を下げて." }),
        commentBody: Type.Optional(Type.String({ description: "Optional markdown comment to record the rationale." })),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_assign_issue",
      label: "Propose Assign Issue",
      description: "Propose changing an issue assignee. This does not execute the mutation.",
      promptSnippet: "Use this when ownership should change.",
      commandType: "assign_issue",
      parameters: Type.Object({
        issueId: Type.String({ description: "Issue identifier like AIC-123." }),
        assignee: Type.String({ description: "Assignee display name, email, or username." }),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_add_comment",
      label: "Propose Add Comment",
      description: "Propose adding a markdown comment to an issue. This does not execute the mutation.",
      promptSnippet: "Use this when the right action is to record context on an issue without changing status.",
      commandType: "add_comment",
      parameters: Type.Object({
        issueId: Type.String({ description: "Issue identifier like AIC-123." }),
        body: Type.String({ description: "Markdown comment body." }),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_add_relation",
      label: "Propose Add Relation",
      description: "Propose adding a relation between issues. This does not execute the mutation.",
      promptSnippet: "Use this when a dependency should be made explicit.",
      commandType: "add_relation",
      parameters: Type.Object({
        issueId: Type.String({ description: "Source issue ID." }),
        relatedIssueId: Type.String({ description: "Related issue ID." }),
        relationType: Type.String({ description: "blocks or blocked-by." }),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
    createProposalTool({
      name: "propose_set_issue_parent",
      label: "Propose Set Issue Parent",
      description: "Propose making one issue a child of another issue. This does not execute the mutation.",
      promptSnippet: "Use this when the user explicitly asks to make AIC-123 a child task of AIC-456.",
      commandType: "set_issue_parent",
      parameters: Type.Object({
        issueId: Type.String({ description: "Child issue identifier like AIC-123." }),
        parentIssueId: Type.String({ description: "Parent issue identifier like AIC-456." }),
        reasonSummary: Type.String({ description: "Short reason for this proposal." }),
        evidenceSummary: Type.Optional(Type.String({ description: "Short evidence summary." })),
        dedupeKeyCandidate: Type.Optional(Type.String({ description: "Stable dedupe key when you can infer one." })),
      }),
    }),
  ];
}
